#require 'spec_helper'
#
## This spec was generated by rspec-rails when you ran the scaffold generator.
## It demonstrates how one might use RSpec to specify the controller code that
## was generated by Rails when you ran the scaffold generator.
##
## It assumes that the implementation code is generated by the rails scaffold
## generator.  If you are using any extension libraries to generate different
## controller code, this generated spec may or may not pass.
##
## It only uses APIs available in rails and/or rspec-rails.  There are a number
## of tools you can use to make these specs even more expressive, but we're
## sticking to rails and rspec-rails APIs to keep things simple and stable.
##
## Compared to earlier versions of this generator, there is very limited use of
## stubs and message expectations in this spec.  Stubs are only used when there
## is no simpler way to get a handle on the object needed for the example.
## Message expectations are only used when there is no simpler way to specify
## that an instance is receiving a specific message.
#
#describe EmailPreferencesController do
#
#  # This should return the minimal set of attributes required to create a valid
#  # EmailPreference. As you add validations to EmailPreference, be sure to
#  # update the return value of this method accordingly.
#  def valid_attributes
#    {}
#  end
#
#  # This should return the minimal set of values that should be in the session
#  # in order to pass any filters (e.g. authentication) defined in
#  # EmailPreferencesController. Be sure to keep this updated too.
#  def valid_session
#    {}
#  end
#
#  describe "GET index" do
#    it "assigns all email_preferences as @email_preferences" do
#      email_preference = EmailPreference.create! valid_attributes
#      get :index, {}, valid_session
#      assigns(:email_preferences).should eq([email_preference])
#    end
#  end
#
#  describe "GET show" do
#    it "assigns the requested email_preference as @email_preference" do
#      email_preference = EmailPreference.create! valid_attributes
#      get :show, {:id => email_preference.to_param}, valid_session
#      assigns(:email_preference).should eq(email_preference)
#    end
#  end
#
#  describe "GET new" do
#    it "assigns a new email_preference as @email_preference" do
#      get :new, {}, valid_session
#      assigns(:email_preference).should be_a_new(EmailPreference)
#    end
#  end
#
#  describe "GET edit" do
#    it "assigns the requested email_preference as @email_preference" do
#      email_preference = EmailPreference.create! valid_attributes
#      get :edit, {:id => email_preference.to_param}, valid_session
#      assigns(:email_preference).should eq(email_preference)
#    end
#  end
#
#  describe "POST create" do
#    describe "with valid params" do
#      it "creates a new EmailPreference" do
#        expect {
#          post :create, {:email_preference => valid_attributes}, valid_session
#        }.to change(EmailPreference, :count).by(1)
#      end
#
#      it "assigns a newly created email_preference as @email_preference" do
#        post :create, {:email_preference => valid_attributes}, valid_session
#        assigns(:email_preference).should be_a(EmailPreference)
#        assigns(:email_preference).should be_persisted
#      end
#
#      it "redirects to the created email_preference" do
#        post :create, {:email_preference => valid_attributes}, valid_session
#        response.should redirect_to(EmailPreference.last)
#      end
#    end
#
#    describe "with invalid params" do
#      it "assigns a newly created but unsaved email_preference as @email_preference" do
#        # Trigger the behavior that occurs when invalid params are submitted
#        EmailPreference.any_instance.stub(:save).and_return(false)
#        post :create, {:email_preference => {}}, valid_session
#        assigns(:email_preference).should be_a_new(EmailPreference)
#      end
#
#      it "re-renders the 'new' template" do
#        # Trigger the behavior that occurs when invalid params are submitted
#        EmailPreference.any_instance.stub(:save).and_return(false)
#        post :create, {:email_preference => {}}, valid_session
#        response.should render_template("new")
#      end
#    end
#  end
#
#  describe "PUT update" do
#    describe "with valid params" do
#      it "updates the requested email_preference" do
#        email_preference = EmailPreference.create! valid_attributes
#        # Assuming there are no other email_preferences in the database, this
#        # specifies that the EmailPreference created on the previous line
#        # receives the :update_attributes message with whatever params are
#        # submitted in the request.
#        EmailPreference.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
#        put :update, {:id => email_preference.to_param, :email_preference => {'these' => 'params'}}, valid_session
#      end
#
#      it "assigns the requested email_preference as @email_preference" do
#        email_preference = EmailPreference.create! valid_attributes
#        put :update, {:id => email_preference.to_param, :email_preference => valid_attributes}, valid_session
#        assigns(:email_preference).should eq(email_preference)
#      end
#
#      it "redirects to the email_preference" do
#        email_preference = EmailPreference.create! valid_attributes
#        put :update, {:id => email_preference.to_param, :email_preference => valid_attributes}, valid_session
#        response.should redirect_to(email_preference)
#      end
#    end
#
#    describe "with invalid params" do
#      it "assigns the email_preference as @email_preference" do
#        email_preference = EmailPreference.create! valid_attributes
#        # Trigger the behavior that occurs when invalid params are submitted
#        EmailPreference.any_instance.stub(:save).and_return(false)
#        put :update, {:id => email_preference.to_param, :email_preference => {}}, valid_session
#        assigns(:email_preference).should eq(email_preference)
#      end
#
#      it "re-renders the 'edit' template" do
#        email_preference = EmailPreference.create! valid_attributes
#        # Trigger the behavior that occurs when invalid params are submitted
#        EmailPreference.any_instance.stub(:save).and_return(false)
#        put :update, {:id => email_preference.to_param, :email_preference => {}}, valid_session
#        response.should render_template("edit")
#      end
#    end
#  end
#
#  describe "DELETE destroy" do
#    it "destroys the requested email_preference" do
#      email_preference = EmailPreference.create! valid_attributes
#      expect {
#        delete :destroy, {:id => email_preference.to_param}, valid_session
#      }.to change(EmailPreference, :count).by(-1)
#    end
#
#    it "redirects to the email_preferences list" do
#      email_preference = EmailPreference.create! valid_attributes
#      delete :destroy, {:id => email_preference.to_param}, valid_session
#      response.should redirect_to(email_preferences_url)
#    end
#  end
#
#end
